#!/bin/bash

# agenda directory:
AGENDA_DIR="$HOME/Documents/Agenda/"

currentDay=$(date +%u) # the current day in the week

# choosing the write day date (which is the date of the SATURDAY of the current
# week):
currentSaturdayDate=$(expr $(date +%d) + 6 - $currentDay)

# look in the agenda dirctory if the current todo list exists:
file=$(ls $AGENDA_DIR | grep "$currentSaturdayDate$(date +%m%Y).todo")

# if the file is not already created:
if [ -z $file ]
then
  file="$currentSaturdayDate$(date +%m%Y).todo"
cat << EOF >> $AGENDA_DIR$file
---
title: TODOS WE $(date +%d-%m-%Y)
---


# Cours

- [ ] TODO


# Maison

- [ ] TODO


# Valise

- [ ] TAKE
EOF
fi

# Open the agenda file
nvim "$AGENDA_DIR$file"
