#!/bin/bash


# Creating alias for config add command :
config_add () {
    /usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME add $1
}

###############################################################################
# ADDINGS :
###############################################################################

# Window manager :
config_add $HOME/.xmonad/img/
config_add $HOME/.xmonad/README.md
config_add $HOME/.xmonad/xmonad.hs
config_add $HOME/.xmonad/**/*.hs
config_add $HOME/.config/xmobar
config_add $HOME/.config/picom.conf

# vim :
# config_add /home/drfailer/.config/nvim/

# mutt :
# use mutt wizard

# Ranger :
config_add $HOME/.config/ranger/

# alacritty :
config_add $HOME/.config/alacritty/

# zsh :
config_add $HOME/.zshenv
config_add $HOME/.config/zsh/.zshrc
config_add /home/drfailer/.config/zsh/src/

# zathura
config_add $HOME/.config/zathura/

# tmux
config_add $HOME/.config/tmux/

# scripts:
config_add $HOME/.scripts/utils/

# Xinit:
config_add $HOME/.xinitrc
config_add /home/drfailer/.Xresources

# ghci:
config_add $HOME/.ghci

###############################################################################
# COMMIT AND PUSH:
###############################################################################

echo "config files added."
sleep 1

# commiting
if [[ $@ != '' ]]; then
    /usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME commit -m "$@"
else
    /usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME commit -m "new update"
fi

echo "commiting done"
sleep 1

# push
/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME push
