#!/bin/bash

set -euo pipefail

alpha=0.75
# alpha=0.88
# alpha=0.92

# changing the theme by default
if [ $# -eq 0 ]; then
  chosen=$(ls ~/.config/alacritty/themes/ | dmenu -l 20 -p 'theme: ')

  # replacement in the file
  if [ ! -z $chosen ]; then
    sed "s/- ~\/.config\/alacritty\/themes\/.*\.yml/- ~\/.config\/alacritty\/themes\/$chosen/" ~/.config/alacritty/alacritty.yml > /tmp/alacritty-tmp.yml
    mv /tmp/alacritty-tmp.yml ~/.config/alacritty/alacritty.yml
  fi
elif [ $# -eq 1 ]; then
  if [ -z $(grep "opacity: 0\..*$" ~/.config/alacritty/alacritty.yml) ]; then
    sed "s/opacity: 1.0/opacity: $alpha/" ~/.config/alacritty/alacritty.yml > /tmp/alacritty-tmp.yml
    mv /tmp/alacritty-tmp.yml ~/.config/alacritty/alacritty.yml
  else
    sed "s/opacity: 0\..*/opacity: 1.0/" ~/.config/alacritty/alacritty.yml > /tmp/alacritty-tmp.yml
    mv /tmp/alacritty-tmp.yml ~/.config/alacritty/alacritty.yml
  fi
fi

