#!/bin/bash

chosen=$(ls ~/.config/alacritty/themes/ | dmenu -l 20 -p 'theme: ')

# replacement in the file
if [ ! -z $chosen ]; then
  sed "s/- ~\/.config\/alacritty\/themes\/.*\.yml/- ~\/.config\/alacritty\/themes\/$chosen/" ~/.config/alacritty/alacritty.yml > /tmp/alacritty-tmp.yml
  mv /tmp/alacritty-tmp.yml ~/.config/alacritty/alacritty.yml
fi
