#!/bin/bash

# variables
BULK_FILE=bulk-tmp.txt
old_names=()
new_names=()

# creating array of old file names
for f in $(ls $PWD); do
  old_names+=($f)
done

# genate the bulkrename file
for old in ${old_names[@]}; do
  printf "%s\n" $old >> $BULK_FILE
done

# bulkrename
$EDITOR $BULK_FILE

# creating array of new file names
for l in $(cat $BULK_FILE); do
  new_names+=($l)
done

# check the size of the tables
if [ ${#old_names[@]} -eq  ${#new_names[@]} ]
then
  # rename files
  for ((i=0; i<${#old_names[@]}; i++))
  do
    if [ ! ${old_names[$i]} == ${new_names[$i]} ] && [ ${new_names[$i]} != "-" ]
    then
      cp -r ${old_names[$i]} ${new_names[$i]}
      # verify if the copy is write before deletion
      if [ -z $(diff ${old_names[$i]} ${new_names[$i]}) ]
      then
        rm -rf ${old_names[$i]}
      else
        echo "ERROR: on ${old_names[$i]}."
      fi
    elif [ ${new_names[$i]} == "-" ]
    then
      rm -rf ${old_names[$i]}
    fi
  done
else
  echo "ERROR: you have to keep all the old names in the files"
fi

# rename the files
rm $BULK_FILE
