#!/bin/bash

compileC() {
    execFileName=$(echo "$1" | sed 's/\.c//g')
    ldflags=""

    # test if math.h is included:
    if [ ! -z "$(grep "<math.h>" $1)" ]; then
        ldflags="-lm"
    fi

    # compile command:
    gcc -Wall -Wextra -o $execFileName $1 $flags
}

# user pandoc to make a pdf from a markdown file
mdpandoc() {
    tableopt='--from=markdown+pipe_tables'
    out=$(echo $1 | sed 's/\.md$/\.pdf/') # generate output name
    pandoc -o $out $1 $tableopt
}

compile() {
    case $1 in
	*.c) compileC $1 ;;
	*.md) mdpandoc $1 ;;
	*.tex) pdflatex $1 ;;
	*.py) python3 $1 ;;
	*.hs) ghc -dynamic $1 ;;
	*.java) javac $1 ;;
	*) echo "unknow filetype" ;;
    esac
}
