#!/usr/bin/env bash

PATH_TO_CPPREF=$HOME/.local/share/cppreference/reference/en/

choice=$(fzf --walker-root=$PATH_TO_CPPREF --prompt='cppref> ' --layout=reverse --height=20)

if [ ! -z $choice ]; then
    brave $choice & 2> /dev/null
fi
