#!/bin/bash

# get emacs process (and only this line, don't catch the line with grep process)
emacs_proc=$(echo $procs | grep "[0-9] emacs --daemon")

if [[ -z $emacs_proc ]] # be shure to kill emacs if it's running
then
    emacs --daemon
    notify-send "emacs daemon started"
else
    kill $(echo $emacs_proc | awk '{ print $2 }')
    emacs --daemon
    notify-send "emacs daemon restarted"
fi
