#!/bin/bash

set -euo pipefail

# secify directory and collect options
chose_files() {
  case $1 in
    do) echo $(find ~/Downloads/ | fzf -m) ;;
    dc) echo $(find ~/Documents/ | fzf -m) ;;
    de) echo $(find ~/Desktop/ | fzf -m) ;;
    c) echo $(find ~/.config/ | fzf -m) ;;
    l) echo $(find ~/.local/ | fzf -m) ;;
    *)
      if [ -d $1 ]; then
        # echo $(find $1 | fzf -m)
        echo $(ls -d $1* | fzf -m) # we don't list recursively here
      else
        echo $(find $HOME | fzf -m)
      fi
      ;;
  esac
}

# the user can specify a location
if [ $# -eq 2 ]; then
  location="$2/"
else
  location=none
fi

# handle main options
choices=$(chose_files $location)
echo $choices
if [[ "$choices" != "$location" ]]; then
  case $1 in
    mv) # move the chosen files
      for c in $choices; do
        mv $c $PWD
      done
      ;;
    cp) # copy the chosen files
      for c in $choices; do
        cp -r $c $PWD
      done
      ;;
    *) echo "ERROR: unknown option." ;;
  esac
fi
