#!/bin/bash

set -euo pipefail

# the user can specify a location
location=none
if [ $# -eq 2 ]; then
  location="$2/"
fi


# secify directory and collect options
chose_files() {
    if [ -d $1 ]; then
        echo $(fzf -m --walker=file,dir,hidden --walker-root="$1")
    else
        echo $(fzf --walker-root="$HOME")
    fi
}

run_cmd() {
    choices=$(chose_files $location)
    if [ ! -z "$choices" ]; then
        for c in $choices; do
            $1 $c $PWD
        done
    fi
}

# handle main options
case $1 in
    mv) run_cmd "mv" ;;
    cp) run_cmd "cp -r" ;;
    cd) echo $(fzf --walker=dir) ;;
    *) echo "ERROR: unknown option." ;;
esac
