#!/bin/bash

###############################################################################
# TITLE: note
# AUTHOR: drfailer
# DATE: Wed Nov 23 11:35:08 AM CET 2022
# DESCRIPTION: Simple note taking system using dmenu
# REQUIREMENTS: dmenu, pandoc
###############################################################################

set -euo pipefail

###############################################################################
# Global variables:
###############################################################################
# Global variable for the note directory
NOTE_DIR="$HOME/.local/share/notes"

# Global variable for tag and file (not const):
tag=""
file=""

###############################################################################
# Help message:
###############################################################################
displayHelpMessage() {
cat << ENDOFMESSAGE
Usage: note <option>

Available options:
  -e, edit      launch the app in edit mode
  -r, read      launch the app in read mode
  -a, add       add notes or images
  -i, img       insert an image from the image directory
  -h, --help    display help message

Notes:
* If the app is launched without any option, it automatically startup in read
  mode.
* With the `noexport`, the script will not generate a pdf for the current note.
ENDOFMESSAGE
}

###############################################################################
# Utilis functions:
###############################################################################

readTag() {
  tag=$(ls $1 | dmenu -i -l 20 -p "Chose a Tag: ")
}

readTopic() {
  file=$(ls $1 | sed -e 's/.pdf//g' | dmenu -i -l 20 -p "Chose a Topic: ")
}

warningMessage() {
  resp=$(printf "no\nyes\n" | dmenu -p 'confirme deletion: ')
  if [[ $resp =~ yes ]]; then
    if [[ $1 =~ \.md ]]; then
      rm $1
      rm $(echo "$1" | sed -e 's/src/build/g' | sed -e 's/\.md/\.pdf/g')
    else
      rm -rf $1
      rm -rf $(echo "$1" | sed -e 's/src/build/g')
      rm -rf $(echo "$1" | sed -e 's/src/img/g')
    fi
  fi
}

# Tag selection (directory):
choseTag() {
  tag=$(printf "$(ls $1)\nremove-mode\n" | dmenu -i -l 20 -p "Select a Tag: ")
  path="$1/$tag"
  if [[ $tag != '' && $tag != "remove-mode" ]]; then
    # create directory in build:
    buildpath=$(echo $path | sed -e 's/src/build/g')
    if [[ ! -d $buildpath ]]; then
      mkdir -p $buildpath
    fi
    # create directory in img:
    imgpath=$(echo $path | sed -e 's/src/img/g')
    if [[ ! -d $imgpath ]]; then
      mkdir -p $imgpath
    fi
    # create directory in src:
    if [[ ! -d $path ]]; then
      mkdir -p $path
    fi
  elif [[ $tag == "remove-mode" ]]; then
    toremove=$(ls $1 | dmenu -i -l 20 -p "! remove-mode: ")
    if [[ $toremove != '' ]]; then
      warningMessage "$1/$toremove"
    fi
  fi
}


# Topic selection (markdown file):
choseTopic() {
  topic=$(printf "$(ls $1)\nremove-mode\n" | sed -e 's/\.md//g' | dmenu -i -l 20 -p "Select a Topic: ")
  if [[ $topic != '' && $topic != "remove-mode" ]]; then
    file="$1/$topic.md"
    if [[ ! -f $file ]]; then
      touch $file
cat << EOF > $file
---
title: $(echo "$topic" | sed -e 's/.*/\u&/g' | sed -e 's/_/ /g')
author: $USER
tag: [$tag, noexport]
---
EOF
    fi
  elif [[ $topic == "remove-mode" ]]; then
    toremove=$(ls $1 | dmenu -i -l 20 -p "! remove-mode: ")
    if [[ $toremove != '' ]]; then
      warningMessage "$1/$toremove"
    fi
  fi
}

# use pandoc to create a pdf if required
compile() {
  if [[ -z $(grep "^tag: " $1 | grep "noexport") ]]; then
    pandoc -V geometry:margin=1in -o "$(echo $1 | sed -e 's/.md/.pdf/g' | sed -e 's/src/build/g')" $1 2> /dev/null
  fi
}

# Function that handle edit mode (the app has been lauched using -e flag)
editNote() {
  choseTag  "$NOTE_DIR/src"
  if [[ $tag != "" && $tag != "remove-mode" ]]; then
    choseTopic  "$HOME/.local/share/notes/src/$tag"
  fi
  if [[ $file != "" && $file != "remove-mode" ]]; then
    st -e nvim -c % "$file" && compile "$file"
  fi
}

# Function that handle read mode (the app has been lauched using -r flag)
readNote() {
  readTag "$NOTE_DIR/build"
  if [[ ! -z $tag && -d  "$NOTE_DIR/build/$tag" ]]; then
    readTopic "$NOTE_DIR/build/$tag"
  fi
  if [[ ! -z $file && -f "$NOTE_DIR/build/$tag/$file.pdf" ]]; then
    zathura "$NOTE_DIR/build/$tag/$file.pdf"
  fi
}

# add notes or images
addNote() {
  # get files to add
  files=$@
  files=( "${files[@]/-a}" )

  # chose a tag
  readTag "$NOTE_DIR/build"
  if [[ ! -z $tag && $tag != "remove-mode" && ! -d  "$NOTE_DIR/build/$tag" ]]; then
    path="$NOTE_DIR/src/$tag"
    mkdir -p $(echo $path | sed -e 's/src/build/g') # create directory in build
    mkdir -p $(echo $path | sed -e 's/src/img/g')   # create directory in img
    mkdir -p $path                                  # create directory in src
  fi
  for f in $files; do
    case $f in
      *.pdf)
        mv $f "$NOTE_DIR/build/$tag"
        ;;
      *.md)
        mv $f "$NOTE_DIR/src/$tag"
        ;;
      *.png|*.jpg|*.jpeg)
        mv $f "$NOTE_DIR/img/$tag"
        ;;
    esac
  done
}

# print out markdown statement to add a chosen image to a note
insertImg() {
  readTag  "$NOTE_DIR/img/"
  if [[ ! -z $tag ]]; then
    img=$(ls "$NOTE_DIR/img/$tag" | dmenu -l 20 -p "Chose image: ")
    if [[ ! -z $img ]]; then
      echo "![$img]($NOTE_DIR/img/$tag/$img)"
    fi
  fi
}

###############################################################################
# Main function
###############################################################################

main() {
  if [ $# -eq 0 ]
  then
    readNote
  else
    case $1 in
      -e|edit)
        editNote
        ;;
      -r|read)
        readNote
        ;;
      -a|add)
        if [ $# -gt 1 ]; then
          addNote $@
        else
          echo "ERROR: you must specify a file to add."
        fi
        ;;
      -i|img)
        insertImg
        ;;
      -h | --help)
        displayHelpMessage
        ;;
      *)
        echo "Unkown option, try to use --help flag for more info."
        ;;
    esac
  fi
}

# Call main function
main $@
