#!/usr/bin/env bash

vidDir="$HOME/Videos/"

declare -a formatChoices=("mp4 no sound"
                          "avi"
                          "mkv with alsa sound"
                          "mkv with pulse sound"
                          )

declare -a outputName=("out"
                       "newrecord"
                       "demo"
                       )

DISPLAY_OFFSET=1366,0

format=$(echo "$(printf '%s\n' "${formatChoices[@]}")" | dmenu -l 20 -p 'video format: ')
if [ ! -z "$format" ]; then
    name=$(echo "$(printf '%s\n' "${outputName[@]}")" | dmenu -l 20 -p 'output name: ')
    if [ ! -z "$name" ]; then
        case $format in
            "mp4 no sound")
                notify-send "Record started:" "mp4 no sound"
                ffmpeg -f x11grab -y -r 25 -s 1920x1080 -i $DISPLAY+$DISPLAY_OFFSET "$vidDir/$name.mp4"
                ;;
            "avi")
                notify-send "Record started:" "avi"
                ffmpeg -f x11grab -y -r 25 -s 1920x1080 -i $DISPLAY+$DISPLAY_OFFSET -vcodec huffyuv $vidDir$name.avi
                ;;
            "mkv with alsa sound")
                notify-send "Record started:" "mkv with alsa sound"
                ffmpeg -f x11grab -y -r 25 -s 1920x1080 -i $DISPLAY+$DISPLAY_OFFSET -f alsa -ac 2 -i hw:2 $vidDir$name.mkv
                ;;
            "mkv with pulse sound")
                notify-send "Record started:" "mkv with pulse sound"
                ffmpeg -f x11grab -y -r 25 -s 1920x1080 -i $DISPLAY+$DISPLAY_OFFSET -f pulse -ac 2 -i default $vidDir$name.mkv
                ;;
            *)
                notify-send "Unknown record option!"
                ;;
        esac
    fi
fi
