#!/usr/bin/env bash

SSH_CMD="ssh"
SFTP_CMD="sftp"
PATH_TO_HOST_FILE="$HOME/.local/share/hosts.txt"
host=$(cut -d '|' -f1 $PATH_TO_HOST_FILE | dmenu -l 20 -p 'ssh: ')

if [[ $(grep "^$host|" $PATH_TO_HOST_FILE | wc -l) != 0 ]]; then
    if [[ ! $host =~ ^quit.*$ && $host != '' ]]; then
        host_ip=$(grep "^$host" $PATH_TO_HOST_FILE | cut -d '|' -f2)
        if [[ $# == 1 && $1 == 'sftp' ]]; then
            $SFTP_CMD $host_ip
        else
            $SSH_CMD $host_ip
        fi
    fi
fi
