# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[❯](bold blue)[❯](bold yellow)[❯](bold #c678dd)"
error_symbol = "[❯](bold blue)[❯](bold yellow)[❯](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# oneline prompt
[line_break]
disabled = true
