#!/usr/bin/env bash

URL='http://edt.uca.fr/jsp/custom/modules/plannings/anonymous_cal.jsp?resources=12589&nbWeeks=3&calType=ical&projectId=6'
wget $URL -O $HOME/.scripts/utils/cal/edt.ics
# grep -e "SUMMARY:*" -e "LOCATION:*" -e "DESCRIPTION:*" edt.ics
sed -e 's/UID.*\n$//g' -e 's/\\n\\n(Modifié.*//g' -e 's/ .*)\n//g' edt.ics
