[colors.primary]
background = "0xf9f5d7"
foreground = "0x504945"

[colors.cursor]
text = "0xfbf1c7"
cursor = "0x504945"

[colors.normal]
black = "0xfbf1c7"
red = "0x9d0006"
green = "0x79740e"
yellow = "0xb57614"
blue = "0x076678"
magenta = "0x8f3f71"
cyan = "0x427b58"
white = "0x504945"

[colors.bright]
black = "0xbdae93"
red = "0x9d0006"
green = "0x79740e"
yellow = "0xb57614"
blue = "0x076678"
magenta = "0x8f3f71"
cyan = "0x427b58"
white = "0x282828"
