[colors.bright]
black = "#867462"
blue = "#A3A9CE"
cyan = "#89B3B6"
green = "#85B695"
magenta = "#CF9BC2"
red = "#D47766"
white = "#ECE1D7"
yellow = "#EBC06D"

[colors.normal]
black = "#0A0A0A"
blue = "#7F91B2"
cyan = "#7B9695"
green = "#78997A"
magenta = "#B380B0"
red = "#BD8183"
white = "#ECE1D7"
yellow = "#E49B5D"

[colors.primary]
background = "#000000"
foreground = "#ECE1D7"
