[colors.bright]
black = "#535353"
blue = "#79a8ff"
cyan = "#4ae2f0"
green = "#70b900"
magenta = "#f78fe7"
red = "#ef8b50"
white = "#ffffff"
yellow = "#c0c530"

[colors.normal]
black = "#323232"
blue = "#2fafff"
cyan = "#00d3d0"
green = "#44bc44"
magenta = "#feacd0"
red = "#ff8059"
white = "#ffffff"
yellow = "#d0bc00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
cursor = "#f4f4f4"
text = "#000000"

[colors.selection]
background = "#3c3c3c"
text = "#ffffff"
